### ISSUE TITLE
sys.path is not set to include the cwd

### ISSUE THREAD

**Issue by ri0t** [rlguy/FantasyMapGenerator#2]
Thanks for fixing the string conversion bug. Now i bumped into another one that is probably 3.x  specific.
EDIT: Nope, that also happens on 2.7!

I could build the binary now, but it couldn't import the render module:

> ModuleNotFoundError: No module named 'render'

So, i searched a bit and i think it is related to the CWD not being in the current sys.path:
[Stackoverflow about sys.path with pyimport](http://stackoverflow.com/questions/13422764/why-does-pyimport-import-fail-to-load-a-module-from-the-current-directory)

I tried adding it but failed because the _get_PyString_fromString function returns a bytes.
So i did it via 

> PyRun_SimpleString("sys.path.append('/home/riot/src/FantasyMapGenerator/build')");

and it was able to import ther render module.

Afterwards i ran into two problems:
* 3.5 - "Error: function not in module dict"
* 3.6 - couldn't import cairo, probably a cairo bug: ModuleNotFoundError: No module named 'cairo._cairo' 

I'd rather not open tickets for those, as i don't know whats going on with 3.5 and i think  the 3.6-one is not related to this project. Help would be appreciated ;)

**Comment by rlguy** [comment]
Hello ri0t,

Thank you very much for testing the program and letting me know what is going wrong. I am sorry you are running into these errors!

I have only been able to test the program using Python 2.7 and Python 3.2. I can't seem to get the embedded Python libraries to work correctly for 3.5 or 3.6 on my machine.

I have updated the repository to add the directory containing the Python rendering code to sys.path.

I have also updated _get_PyString_fromString to use PyUnicode_FromString method instead of PyBytes_FromString. I think this would be more correct, and maybe it will fix the "function not in module dict" error.

I am not sure what is causing the "ModuleNotFoundError: No module named 'cairo._cairo'" error for you. I have found that if I use a version of cairo that is build for a different of Python, I will get the same error.  This happened when I used a cairo build for Python 2.7 in Python 3.2.

I hope this helps. Please let me know if the changes end up fixing any of these issues.

Best Regards,
Ryan

**Comment by ri0t** [comment]
Totally works! Thanks a lot :) 🍸 🎉 🥇 
Oh: and NIIIIIIICE *bg*
